[package]
name = "serde_derive_tests_no_std"
version = "0.0.0"
publish = false

[dependencies]
libc = { version = "0.2", default-features = false }
serde2 = { path = "../../serde", default-features = false }
serde2_derive = { path = "../../serde_derive" }

[workspace]
